version: '3.7'

services:
  proxy:
    env_file:
      - .env.production.local
    image: glavermi/perizia_app:latest
    build:
      context: ./
      dockerfile: DockerfileNginx
    ports:
      - '7000:80'
    restart: 'unless-stopped'
    networks:
      - backend
    depends_on:
      - server
  server:
    env_file:
      - .env.production.local
    deploy:
      replicas: 1
    image: glavermi/perizia_service:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000'
    restart: 'unless-stopped'
    networks:
      - backend
    volumes:
      - /root/perizia/ServerApp/img/:/root/ServerApp/img

networks:
  backend:
    driver: bridge

volumes:
  perizia_img: